### ISSUE TITLE
项目管理脚本

### ISSUE THREAD

**Issue by skb666** [Neutree/c_cpp_project_framework#3]
每次新建项目阶段需要进行几个固定文件的复制；编译完成后需要手动去 ./build/ 中运行可执行程序
能否添加一个脚本去管理，或者改进一下 project.py
实现类似这样的功能：https://github.com/skb666/c_sdk/blob/base/manage.py

**Comment by Neutree** [comment]
确实可以， 因为主要是给嵌入式程序做的，所以没有 run， run命令确实可以加上去。

create 也可以加一个，只不过始终得有个脚本，我有个想法就是用户可以在任意工程目录下（比如example目录），因为已经有 project.py 了，直接 python project.py create 指定新的位置创建就好了

**Comment by Neutree** [comment]
更新了一下， 支持了 run 命令。
另外支持方便地添加命令，方法看说明：
[README.md 增加新的命令](https://github.com/Neutree/c_cpp_project_framework/blob/master/README_ZH.md#%E5%A2%9E%E5%8A%A0%E6%96%B0%E7%9A%84%E5%91%BD%E4%BB%A4)

**Comment by skb666** [comment]
方便好用👍
