### ISSUE TITLE
组件分类

### ISSUE THREAD

**Issue by skb666** [Neutree/c_cpp_project_framework#4]
建议组件 components 分为 3 类：
1. 全局 SDK 组件，目录 components
2. 项目共享组件，目录 <project_path_name>/components，例： examples/components
3. 项目私有组件，目录 <project_path_name>/<project_name>/<component_name>，例： examples/demo1/libabc

场景说明： 多个独立项目，每个独立项目包含几个子项目，子项目用到一些组件可以放项目私有组件目录[3]，多个子项目共享组件放到项目共享组件目录[2]，每个独立项目都用的 SDK 的组件放到全局 SDK 组件目录[1]。

其他说明：
项目共享组件的使用场景：独立项目的 test 代码以及 examples，用到与改项目相同的组件；
这个编译框架作为跟 vcpkg 这样的基础设施，独立于项目之外工作，更方便复用和推广；
方便后期定制 vscode 插件；

**Comment by Neutree** [comment]
目前已经支持的放component的路径为：
* sdk_path/components 目录： https://github.com/Neutree/c_cpp_project_framework/blob/3d9e278898f4e718bacedb12d51d72db7930e67e/tools/cmake/compile.cmake#L213
* project_path/ 目录： https://github.com/Neutree/c_cpp_project_framework/blob/3d9e278898f4e718bacedb12d51d72db7930e67e/tools/cmake/compile.cmake#L232

也就是你提到的 1 和 3 其实已经满足了，只是2是否有必要有待商榷，因为目前的设计来讲，项目共享的组件默认都认为放到 sdk/component 目录下就好了，比较简单；
再加一个扫描额外的component路径看是否有必要以及怎么实现，我初步想到有个最简单的方法就是加一个扫描额外compents路径的环境变量

**Comment by skb666** [comment]
我觉得这样就可以：

[c_cpp_project_framework/tools/cmake/compile.cmake](https://github.com/Neutree/c_cpp_project_framework/blob/3d9e278898f4e718bacedb12d51d72db7930e67e/tools/cmake/compile.cmake) 添加

```cmake
# Find components in projects' shared components folder, register components
file(GLOB shared_component_dirs ${PROJECT_SOURCE_DIR}/../components/*)
# ...
```

[c_cpp_project_framework/Kconfig](https://github.com/Neutree/c_cpp_project_framework/blob/3d9e278898f4e718bacedb12d51d72db7930e67e/Kconfig) 添加

```kconfig
osource "${PROJECT_PATH}/../components/*/Kconfig"
```

增加对 `<app>/../components/` 目录的扫描支持，将 `<app>/../` 看作 project_path

```text
project_name（相当于目前的 examples 目录）
├── components
│   ├── component1
│   └── component2
├── app_target
│   └── component3
├── lib_target
│   ├── component4
│   └── component5
├── example1
└── example2
```

当一个项目里包含多个应用、共用组件、样例程序时，可以直接 github 上传项目文件夹，而无需包含该编译框架。
当编译框架更新时，也无需同步修改使用了该框架的仓库；直接升级编译框架，通过设置 MY_SDK_PATH 系统环境变量使用。
由该编译框架模板生成的 SDK，用户使用时 `sdk/component` 放置官方提供的组件，`project_path/components` 放个人添加的共享可复用组件。

**Comment by Neutree** [comment]
这样也行，得测试一下如果没有这个文件夹会不会报错

**Comment by skb666** [comment]
> 这样也行，得测试一下如果没有这个文件夹会不会报错

测试过，没有这个文件夹不会报错

**Comment by skb666** [comment]
我用模板生成了一个仓库 [PyBuildKit](https://github.com/skb666/PyBuildKit)，在设置 `MY_SDK_PATH` 后，把 [template](https://github.com/skb666/PyBuildKit/tree/master/template) 文件夹拷贝出去后用 `vscode` 打开；可以配合新版本的 `CMake Tools (>=1.13.40)` 正常工作。
该插件目前已支持 [Multi Root and Multi Project](https://github.com/microsoft/vscode-cmake-tools/pull/2835)，可通过设置 `.vscode/setting.json` 使底部状态栏支持切换要编译的目标文件夹，利用 `UI` 支持让这个构建框架的使用变得更直观和方便。

**Comment by Neutree** [comment]
很好 等会儿试试

**Comment by Neutree** [comment]
已经合并了
