### ISSUE TITLE
使用 cmake 编译时的代码版本问题

### ISSUE THREAD

**Issue by skb666** [Neutree/c_cpp_project_framework#7]
编译命令：

```bash
cd examples/demo1
cmake -S. -Bbuild
cmake --build build -t all
```

使用 `cmake` 而不是 `python` 进行编译时，若不指定 `CMAKE_BUILD_TYPE` ，遇到以下问题：

![bug](https://github.com/Neutree/c_cpp_project_framework/assets/32807259/255279f2-417d-483e-8612-f33fff8ce22c)

原因应该是 [compile.cmake](https://github.com/Neutree/c_cpp_project_framework/blob/429a7ec/tools/cmake/compile.cmake#L383) 中版本判断错误，导致 `global_config.h` 中 `DEBUG` 与 `RELEASE` 定义的值与传入的宏不一致。

**Comment by Neutree** [comment]
啊确实是bug了，感谢！
